### ISSUE TITLE
X-Frame-Origin: DENY header sent for some pages in the project

### ISSUE THREAD

**Issue by tstaubitz** [readthedocs/readthedocs.org#8380]
## Details
I noticed yesterday that many of the pages in our project don't work anymore as there's an X-Frame-Origin: DENY header sent. It seems completely random which of the pages are affected. The one that still worked yesterday doesn't work anymore today. Others that didn't work yesterday were ok just now. We didn't change anything in between.

All of the pages that don't work have an x-frame-options: DENY header. The ones that do not work, do not have an x-frame-options header at all. While we tried to figure out what's wrong, we found this ticket: https://github.com/readthedocs/readthedocs.org/issues/8377, which seems to be related. Would it be possible that you remove the  x-frame-options header on our side as well?

* Read the Docs project URL: https://teachingteamguidelines.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/teachingteamguidelines/builds/
* Read the Docs username (if applicable): OpenHaPI

## Expected Result
I want to see the complete read-the-docs page in my project. All of them.

## Actual Result
I only see the header and navigation. Some pages show an error (teachingteamguidelines.readthedocs.io refused to connect.) others are displayed correctly.

**Comment by humitos** [comment]
Hi @tstaubitz! The header `X-Frame-Origin: DENY` went out last Tuesday; but yesterday we deployed a fix and it should not be present on documentation pages anymore. Can you share what are the pages that still contain this header? We can take look if there is a mistake from our side.

**Comment by MrSerth** [comment]
Hi @humitos,
many thanks for your quick reply! I've just checked the following page which doesn't work due to the header being sent as part of the response: https://teachingteamguidelines.readthedocs.io/#bestpractices/curriculumdesign/

**Comment by humitos** [comment]
@MrSerth maybe you have the response cached? I don't see header on that URL:

```
$ curl -s -IL https://teachingteamguidelines.readthedocs.io/\#bestpractices/curriculumdesign/ | grep -i frame
$ 
```

and the page loaded by that `#` on behind:

```
$ curl -s -IL https://teachingteamguidelines.readthedocs.io/bestpractices/curriculumdesign/ | grep -i frame
$
```

Does it work if you clean up your local cache?

**Comment by MrSerth** [comment]
Unfortunately, clearing the cache doesn't help and I still get the header when performing the request with cURL:

```shell
$ curl -s -IL https://teachingteamguidelines.readthedocs.io/bestpractices/curriculumdesign/
HTTP/2 200 
date: Thu, 29 Jul 2021 16:00:56 GMT
content-type: text/html
vary: Accept-Encoding
x-amz-id-2: acCn+ZGjnoHJAMB105dYKG7NVx6stCZO3vkUKtLjL8R9tge0B7NrK5NSMa8BnZOrpy4qR26sOTc=
x-amz-request-id: CN99ZQ1KSHBMQGRX
last-modified: Fri, 16 Jul 2021 20:16:24 GMT
etag: W/"153b66fc1f1ddb506108e4607ccc3dc1"
x-served: Nginx-Proxito-Sendfile
x-backend: web-i-034143a3ae5cfae76
x-rtd-project: teachingteamguidelines
x-rtd-version: latest
x-rtd-path: /proxito/html/teachingteamguidelines/latest/bestpractices/curriculumdesign/index.html
x-rtd-domain: teachingteamguidelines.readthedocs.io
x-rtd-version-method: path
x-rtd-project-method: subdomain
referrer-policy: no-referrer-when-downgrade
permissions-policy: interest-cohort=()
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-frame-options: DENY
cf-cache-status: HIT
age: 539
expires: Thu, 29 Jul 2021 18:00:56 GMT
cache-control: public, max-age=7200
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 676790232f534e79-FRA
```

![Bildschirmfoto 2021-07-29 um 18 03 18](https://user-images.githubusercontent.com/7300329/127526057-0f70b253-8b4b-466e-ad21-26e8551e0bf1.png)

**Comment by ericholscher** [comment]
@MrSerth I've cleared our entire cloudflare cache. This web server hasn't existed for a while, so I'm guessing something weird is happening with caching. Can you confirm you're still seeing this?

**Comment by MrSerth** [comment]
@ericholscher Great, thanks for doing so! This resolved our issue and I am now able to access all pages without any issue. 

I was actually quite surprised to see our pages being affected by the `X-Frame-Origin: DENY` header because we didn't use any iframe intentionally but only through the [windmill theme for MkDocs](https://github.com/gristlabs/mkdocs-windmill).

**Comment by ericholscher** [comment]
Interesting -- seems like that theme uses iframes to load the pages? Definitely a new UX I haven't seen much of. Good to know about though.

**Comment by tstaubitz** [comment]
Thanks a lot for this superquick fix.
